#99 Add vaccination eligibility government link
CovidTrackerFr/vitemadose-front pull request #109
Opened 2021-04-22 20:33 UTC by nhumblot

Fix #99

2021-04-22 21:04 UTC, fcamblor commented
Pour information, l'implémentation actuelle donnerait ça :
<img width="1329" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/115783311-000e0f80-a3bd-11eb-90b6-c98d7e58999c.png">

J'aurais bien mis un peu plus en avant l'information, via un "panel" (bon, ça n'existe plus les panels dans bootstrap >3) avec un ℹ️ informatif

Après, la question principale est de savoir si un lien sortant vers le site du gouvernement n'est pas ennuyeux d'un point de vu SEO (@francoisbouchet semblait assez catégorique sur le sujet hier..)

2021-04-22 21:17 UTC, nhumblot commented
> Après, la question principale est de savoir si un lien sortant vers le site du gouvernement n'est pas ennuyeux d'un point de vu SEO (@francoisBouchet semblait assez catégorique sur le sujet hier..)

Je viens de voir la conversation sur le Mattermost, merci pour le signalement, j'avais fait un grand coup de molette sur la journée car trop occupé par le travail. :innocent:

2021-04-22 22:42 UTC, fcamblor commented
Moi personnellement je serais plutôt très en faveur de ce lien qui est utile pour les utilisateurs.

On a énormément de gens qui pensent que parce que le rdv apparaît, alors ils peuvent prendre le rdv les yeux fermés.
Rappeler les règles ne serait vraiment pas du luxe selon moi, et si on le fait, je pense qu'il faut le faire de manière moins discrète que ce que tu as fait :-)

2021-04-24 21:09 UTC, fcamblor commented
Après pas mal de discussions sur le sujet sur Mattermost, je pense qu'il faudrait effectuer les changements suivants :
- Ne plus afficher le message/lien sur le résultat de la recherche, mais afficher un sticky footer pendant quelques secondes (10s ?) après l'affichage de la vue rdv, sans lien vers le site du gouvernement qui pourrait confuser l'internaute dans les options qu'il peut faire sur cet écran de résultat (l'objectif est de lui faire trouver un rdv, pas de lui faire checker s'il est éligible)
![image](https://user-images.githubusercontent.com/603815/115972782-bce4a580-a550-11eb-8fd5-ca9eef078160.png)
- On a évoqué le fait de lister dans un fichier JSON dédié du back une liste de critères d'éligibilité qui seraient affichés sur la home (section "Qui peut se faire vacciner contre la Covid-19 ?" du `APropos`)
<img width="1307" alt="▶️_Général_-_CovidTracker_Mattermost" src="https://user-images.githubusercontent.com/603815/115972957-e94cf180-a551-11eb-8d29-f5b27474fed2.png">
Pour ce second point, je pense qu'il faut le descoper de la PR courante, mais on pourrait créer une issue dédiée pour commencer à travailler sur le sujet et proposer un fichier JSON au back sous forme de PR.

2021-04-25 18:03 UTC, nhumblot commented
@fcamblor je viens de finir une contribution sur owasp dependency check. Je bosse sur tes remarques à ma prochaine disponibilité (demain soir je pense).

2021-04-27 19:21 UTC, nhumblot commented
Disparition après 10s.

![Screenshot_20210427-212039.png](https://user-images.githubusercontent.com/15015617/116299887-856b3880-a79e-11eb-8a69-ec706fc85b6a.png)

![Screenshot_20210427-212049.png](https://user-images.githubusercontent.com/15015617/116299907-8a2fec80-a79e-11eb-88aa-fbcfdd3f9b92.png)

2021-04-28 00:02 UTC, fcamblor requested changes

2021-04-28 00:02 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +        this.eligibilityCriteriaTimeout = setTimeout(async () => {
je pense qu'il faudrait faire un clearTimeout dans le `disconnectedCallback`

2021-04-28 00:02 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +                    <p>Soyons citoyens et respectons les conditions d'éligibilité :-)</p>
Contenu à peut-être changer en quelque chose de plus engageant ?

Quelque chose du type " ⚠️ Les conditions d'éligibilité devront être respectées lors de la prise de rendez-vous sur une plateforme"
(c'est peut-être un peu long...)

2021-04-28 00:03 UTC, fcamblor commented
Pour info, j'ai créé une branche sur le repo qui est du coup visible ici : https://dev.vitemado.se/109-lien-eligibilite/

2021-04-28 00:04 UTC, fcamblor commented on src/views/vmd-rdv.view.scss
> +.eligibility-criteria {
Il faudrait peut-être rajouter un petit coup d'animation pour fadein/fadeout la div progressivement lors de l'affichage/masquage

2021-04-29 06:34 UTC, nhumblot commented on src/views/vmd-rdv.view.ts
> +                    <p>Soyons citoyens et respectons les conditions d'éligibilité :-)</p>
Je propose "Les critères d'éligibilité seront vérifiés pour une prise de rendez-vous" 72 char vs 62 pour "Soyons citoyens et respectons les conditions d'éligibilité :-)".

2021-04-29 06:46 UTC, nhumblot commented on src/views/vmd-rdv.view.scss
> +.eligibility-criteria {
Je regarde ce point.

2021-04-29 07:34 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +                    <p>Soyons citoyens et respectons les conditions d'éligibilité :-)</p>
"⚠️ Les critères d'éligibilité sont vérifiés lors de la prise de rendez-vous" ?
(pour 3 caractères de plus je trouve que c'est mieux perso)

2021-04-29 20:12 UTC, nhumblot commented
@fcamblor, finalement avec ta demande de fade-in, fade-out, je suis venu avec une solution complètement en css ce qui rend le code, je pense, plus simple.

Test effectué sur Chrome et Firefox (Desktop Linux & Smartphone Android).

2021-05-02 22:11 UTC, fcamblor commented
ah oui, trop bien de tout faire juste en CSS 👍

2021-05-02 22:11 UTC, merged