✨feat(search): scroll on focus #114
CovidTrackerFr/vitemadose-front pull request #115
Opened 2021-04-23 16:49 UTC by bilelz

2021-04-25 11:43 UTC, bilelz commented
Hello

Quelqu'un pourrait-il valider le déploiement de cette PR et de la #108  sur l'environnement de test?

Thanks

2021-04-28 22:58 UTC, fcamblor requested changes
Merci pour cette PR 👍 

Je trouve que c'est une bonne idée sur le principe, par contre j'ai un soucis sur le changement de page car ça me fait réaliser que la position de la scrollbar est conservée lors d'un changement de vue.

Il faudrait faire en sorte de trigger un "scroll to top" à chaque changement de vue (à faire dans le `Routing._declareRoute()`)

2021-04-28 22:58 UTC, fcamblor commented on package.json
> +    "smoothscroll-polyfill": "^0.4.4"
Je préfèrerais qu'on utilise des versions fixées afin d'avoir un build reproductible lors d'un nouveau `npm install` :-)

2021-04-28 22:58 UTC, fcamblor commented on src/components/vmd-commune-selector.component.ts
> +smoothscroll.polyfill();
Je préfèrerais déporter tout ce qui concerne "initializations" de ce type :
- soit dans le constructeur du composant `vmd-app`
- soit dans le `index.ts`

(je te laisse le choix de ce que tu trouves le plus pertinent)

2021-04-29 10:27 UTC, bilelz commented on src/components/vmd-commune-selector.component.ts
> +smoothscroll.polyfill();
OK. Merci pour le feedback.
Je viens de pousser un commit prenant en compte tout ça.

2021-05-02 22:04 UTC, fcamblor commented
j'ai revert les changements sur `con.json` / `aux.json` afin qu'on tire ces changements au clair, proprement (cf mes remarques sur #108)

De cette manière, ça me permet de merger la PR :-)

Merci pour cette dernière 👍

2021-05-02 22:04 UTC, merged