Ajout page Chronodose (SEO)
CovidTrackerFr/vitemadose-front pull request #163
Opened 2021-05-07 09:40 UTC by rozierguillaume

2021-05-07 11:44 UTC, Luwangel requested changes

2021-05-07 11:44 UTC, Luwangel commented on src/views/vmd-chronodose.view.ts
> +          Vite Ma Dose présente Chronodose, une fonctionnalité permettant de trouver une dose de vaccin Covid19 en 24h pour tous les plus 18 ans, sans condition d'élibilité. Cette fonctionnalité sera
```suggestion
          Vite Ma Dose présente Chronodose, une fonctionnalité permettant de trouver une dose de vaccin Covid19 en 24h pour tous les plus 18 ans, sans condition d'élibilité. Cette fonctionnalité sera déployée sur Vite Ma Dose d'ici au mercredi 12 mai, disponible sur le <u><a href="https://vitemadose.covidtracker.fr">site internet</a></u>, et les applications mobiles (<u><a href="https://apple.co/3dFMGy3">iOS</a></u> et <u><a href="https://play.google.com/store/apps/details?id=com.cvtracker.vmd2">Android</a></u>).<br>
```

2021-05-07 11:44 UTC, Luwangel commented on src/views/vmd-chronodose.view.ts
> +        // console.log("disconnected callback")
```suggestion
```

2021-05-07 11:56 UTC, rozierguillaume commented
Cette PR est sur main car « urgente »

2021-05-07 12:13 UTC, Luwangel approved these changes
Compris pour la branche main :D

2021-05-07 12:14 UTC, merged

2021-05-09 16:44 UTC, tbroyer commented on src/views/vmd-chronodose.view.ts
> +import globalCss from "../styles/global.scss";
```ts
import {CSS_Global} from "../styles/ConstructibleStyleSheets";
```