Arrêter le polling de maj quand l'une d'elle est détectée #188
CovidTrackerFr/vitemadose-front pull request #200
Opened 2021-05-13 12:00 UTC by Aymerik

Arrêt de la vérification de mise à jour dans le cas où une mise à jour est trouvée
Reprise de la vérification dès lors qu'un refresh est effectué

(cf issue #188)

2021-05-14 13:21 UTC, fcamblor requested changes

2021-05-14 13:21 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +        console.log("lancement boucle");
@Aymerik Serait-il possible d'enlever les `console.log` stp ? :)

2021-05-14 13:21 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +                this.launchCheckingUpdates();
@Aymerik je pense pas que ce soit une bonne idée de démarrer le check de maj ici, car je pense qu'on doit pouvoir appeler le `refreshLieu()` alors que le `setInterval()` est déjà en cours.

J'aurais plutôt : 
- Appelé le `launchCheckingUpdates()` uniquement lors du clic sur le bouton `Rafraîchir`
- Checké (histoire d'être sûr et certain) qu'on démarre le `setInterval()` uniquement si `this.lieuBackgroundRefreshIntervalId` est `undefined`

2021-05-14 13:21 UTC, fcamblor commented on src/views/vmd-rdv.view.ts
> +                    clearInterval(this.lieuBackgroundRefreshIntervalId);
@Aymerik Attention à ne pas oublier de nullifier le `this.lieuBackgroundRefreshIntervalId` après le `clearInterval` ... ou bien, mieux : de mutualiser le `clearInterval` du `disconnectedCallback()` (qui passe le `this.lieuBackgroundRefreshIntervalId` à `undefined`) avec celui-ci

2021-05-14 14:42 UTC, Aymerik commented
Merci pour tes retours @fcamblor 
Je viens d'apporter les correctifs, n'hésite pas à me faire de nouveaux tes retours si tu en as ;-)

2021-05-15 11:33 UTC, merged

2021-05-15 11:33 UTC, fcamblor commented
Impect ! 👌