Simplification de appointment-metadata
CovidTrackerFr/vitemadose-front pull request #204
Opened 2021-05-14 09:20 UTC by pmdartus

* [A11y] - Ajout des attributs `aria-label` et `role` pour les icones
* [Perf] - Rendering conditionnel via d'une expression ternaire pour les champs telephone et vaccin pour au lieux de passer la `display: none`
* [Refactor] Suppression de `.centerIconVertically` qui n'est pas utilisé
* [Refactor] Remplacement du `content` par le default slot

2021-05-14 14:11 UTC, fcamblor requested changes
Je suis OK sur les 2 premiers changements évoqués : ajout du `aria-label`/`role`, suppression du `displayed` et utilisation d'un rendering conditionnel

Le 3ème changement introduit une régression.

Enfin, je trouve le 4ème changement inutile (subjectif en fait ... aussi bien entre votre vision que la mienne)
Je n'ai pas d'opinion forte à absolument conserver ma vision des choses, mais je trouve que faire un changement pour une vision tout autant subjective ne sert à rien.
Ce raisonnement s'applique pour les autres points assez subjectifs (suppression de code "inutile" sur le `styles` et le `disconnectedCallback`) : parfois, je trouve qu'avoir du code (même inutile), ça sert à dire quelque chose :-)

2021-05-14 14:11 UTC, fcamblor commented on src/components/vmd-appointment-metadata.component.ts
> -            <div class="row ${classMap({'align-items-center':!!this.centerIconVertically})}">
@pmdartus Je n'ai pas compris pourquoi avoir fait cette suppression

Elle engendre une régression visuelle (l'icone n'est plus centrée verticalement) : 
Avant : 
<img width="564" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/118281181-3e36b480-b4cd-11eb-90fc-b3e259643257.png">

Après : 
<img width="523" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/118281276-527ab180-b4cd-11eb-8aa4-19b4c74fe3bc.png">

2021-05-14 14:11 UTC, fcamblor commented on src/components/vmd-appointment-metadata.component.ts
> -                  <slot name="content"></slot>
@pmdartus Personnellement, j'aime bien nommer les slots : ça permet de savoir de quoi on parle (et ça permet aussi de rajouter de nouveaux slots facilement si besoin)

2021-05-14 14:11 UTC, fcamblor commented on src/components/vmd-appointment-metadata.component.ts
> -    disconnectedCallback() {
De même que pour la partie `styles`, j'aime bien montrer explicitement qu'on "ne fait rien" lorsque le composant est déconnecté du DOM

2021-05-14 14:11 UTC, fcamblor commented on src/components/vmd-appointment-metadata.component.ts
> -        css`
J'aime bien laisser la facilité de pouvoir définir des css custom au niveau du composant (c'est la raison pour laquelle je laisse ce literal même s'il ne sert à rien)

2021-05-16 17:24 UTC, Luwangel commented on src/components/vmd-appointment-metadata.component.ts
> +                <i class="bi ${this.icon} col-auto" role="img" aria-label="${this.label}"></i>
En lisant le code, j'ai deux avis et je ne sais pas lequel est le meilleur.

1. J'ai l'impression que ces icônes sont des labels pour les textes qu'elles décrivent. On pourrait ajouter une balise `aria-labelledby` sur la balise `p` pour le préciser.
2. J'ai l'impression qu'il n'y a pas besoin de décrire ces icônes parce qu'elles n'apportent rien à l'utilisateur. Ce n'est pas forcément utile de préciser que +33XXXXXX est un numéro de téléphone. Dans ce cas, il est possible d'ajouter la balise `aria-hidden="true"` sur les icônes.

2021-08-05 21:35 UTC, fcamblor commented
Pas d'activité depuis 2 mois et demi sur la PR, je la ferme (ne pas hésiter à se manifester pour la rouvrir)

2021-08-05 21:35 UTC, closed without merging