Mise à jour conditions éligibilité vaccin
CovidTrackerFr/vitemadose-front pull request #251
Opened 2021-06-21 09:02 UTC by a2br

Cette Pull Request est

- [x] Un correctif
- [ ] Une nouvelle fonctionnalité

### Checklist

- [x] Si cette PR résoud une [issue](https://github.com/CovidTrackerFr/vitemadose-front/issues), j'indique son numéro dans les description
- [x] Cette PR vise la branche `dev`
- [x] Elle n'est pas en conflit avec la branche `dev`

### Description

Mise à jour des conditions d'éligibilité au vaccin

![image](https://user-images.githubusercontent.com/62328077/122736041-e2a3d780-d27f-11eb-8f0d-6c1c30b41cf8.png)

2021-06-21 13:11 UTC, Luwangel requested changes
Super ! J'ai juste une remarque sur la vaccination des adolescents.

2021-06-21 13:11 UTC, Luwangel commented on index.html
> +                <p>Toutes les personnes de plus de 12 ans résidant en France sont éligibles à la vaccination contre la Covid-19.</p>
```suggestion
                <p>Tous les adultes de plus de 18 ans résidant en France sont éligibles à la vaccination contre la Covid-19.</p>
                <p>Les adolescents de plus de 12 ans résidant en France sont également éligibles à la vaccination contre la Covid 19 avec l'accord de leurs parents ou responsables légaux (<a class="link-primary text-decoration-underline" href="https://eduscol.education.fr/2792/vaccination-des-jeunes-de-12-18-ans" target="_blank" rel="noreferrer">outils pour sensibiliser ce public à la vaccination</a>.</p>
```

Je pense qu'il faut ajouter la précision "accord avec les parents" pour les jeunes puisque c'est précisé sur le site du gouvernement.

2021-06-21 13:35 UTC, a2br commented
Merci pour ton aide! Je viens de rajouter des changements. C'est dans la description de https://github.com/CovidTrackerFr/vitemadose-front/pull/251/commits/a5a28a885f7bc0a79dccb65bf6d70bda3a478cbe.

![image](https://user-images.githubusercontent.com/62328077/122771109-68d31480-d2a6-11eb-8437-35a5ebe4e545.png)

2021-06-22 07:36 UTC, Luwangel approved these changes

2021-07-17 09:13 UTC, fcamblor commented
LGTM, j'ai changé la target vers `main` pour MEP en suivant :-)

2021-07-17 09:14 UTC, merged

2021-07-17 09:14 UTC, fcamblor commented
Merci pour la contrib @a2br :)