Première PR, nettoyage cosmétique
CovidTrackerFr/vitemadose-front pull request #256
Opened 2021-07-20 21:27 UTC by GillesDebunne

Cette Pull Request est

- [x] Un correctif
- [ ] Une nouvelle fonctionnalité

### Description

Première PR sur cette base de code. 

Quelques modifications mineures et cosmétiques :
- Remplacer le type `void` par `undefined` pour les variables. D'après [la page TS](https://www.typescriptlang.org/docs/handbook/basic-types.html#void) "_Declaring variables of type void is not useful_"
- Changer les quelques `var` utilisés par des `let` et `const` plus TS
- Supprimer le fichier `delay.ts` qui n'est pas utilisé
- Modifier le type `NormalizedSearch`

2021-07-21 07:24 UTC, Luwangel requested changes
Super ! J'ai juste une remarque (voir commentaires).

2021-07-21 07:24 UTC, Luwangel commented on src/state/Autocomplete.ts
> -type NormalizedSearch = string & { __normalized_search: void }
Pourquoi ne pas avoir changé ça en `string & { __normalized_search: undefined }` ?

2021-07-21 08:12 UTC, GillesDebunne commented
Ce champ __normalized_search: n’est jamais utilisé.

Il est même trompeur puisque dans la suite du code, on « cast » des string
en NormalizedSearch avec des `as`.

2021-07-21 13:24 UTC, Luwangel approved these changes

2021-07-22 07:22 UTC, fcamblor commented
Il me semble que cette notation avec le `__normalizedSearch` avait été introduite par @Floby et avait pour objectif de pouvoir contourner le duck typing sur les type alias.

2021-07-22 09:35 UTC, Floby commented
correct, grosso modo c'est de la convention ça ne change pas grand chose à part demander au compilateur de vérifier qu'on est passé par la fonction normalize pour la variable qu'on manipule

2021-07-24 21:23 UTC, GillesDebunne commented
J'ai remis en place le type `string & { _:undefined }` qui évite effectivement le duck typing. J'ai commenté.

J'ai uniformisé l'usage de `Normalized` à la place de `Searchable`.

J'ai aussi éclairci les commentaires autour de la méthode `toFullTextNormalized` partagée.

2021-07-27 08:45 UTC, fcamblor commented on tools/communes-import.ts
> +                // are used to fetch the appropriate pre-computed Commune list computed here.
```suggestion
                // /!\ important note : in this file, these strings are compared to "queries", 
                // which are exclusively composed of the INDEXED_CHARS characters. 
                // Strings.toFullTextNormalized() converts accents to these chars to make
                // this comparison possible.
                // The same method/implementation is used in Autocomplete.ts to create search prefixes 
                // which are used to fetch the appropriate pre-computed Commune list computed here.
```

2021-07-27 08:46 UTC, fcamblor commented
Au-delà de la petite typo que j'ai relevé (et que je te laisse confirmer), c'est OK pour moi.
@GillesDebunne tu voulais itérer encore un peu sur d'autres amélioration ou je merge ? :)

2021-07-27 08:59 UTC, GillesDebunne commented
Ok pour merger

Et pour corriger la typo (ou je le ferai en rentrant cette aprem)

Merci !

2021-07-27 09:43 UTC, merged

2021-07-27 09:43 UTC, fcamblor commented
@GillesDebunne merci à toi pour la PR :)